baseURL = "http://dannypsnl.github.io/rocket"
languageCode = "en-us"
title = "Rocket"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
themeVariant = "red"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/dannypsnl/rocket"
weight = 10
