language: go

go:
  - master

sudo: false
before_script:
  - go get ./...
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

go_import_path:
  - github.com/dannypsnl/rocket

script:
  - go test -v ./...

deploy:
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
