os: Visual Studio 2017
version: "{build}"

platform: x64

clone_folder: c:\gopath\src\github.com\dannypsnl\rocket

environment:
  global:
    GOPATH: C:\gopath
    GO111MODULE: on
    CC: gcc.exe
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
    - GETH_ARCH: 386
      MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      PATH: C:\msys64\mingw32\bin\;C:\Program Files (x86)\NSIS\;%PATH%

build: false
deploy: false

test_script:
  - go get -t -v ./...
  - go test -v ./...
