name: Go
on:
  push:
    branches:
    - '*'
    paths:
    - '**.yml'
    - '**.go'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.yml'
    - '**.go'
  schedule:
  - cron: 0 0 * * *

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.11, 1.12, 1.13, 1.14, 1.15]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: GO111MODULE=on go test -v -count 1 -cover ./...
